/* GENERATED by tools/gen_fonts.py -- do not edit. */

#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t fms_b612_mono_16;
extern const lv_font_t fms_b612_mono_20;
extern const lv_font_t fms_b612_mono_24;
extern const lv_font_t fms_b612_mono_28;
extern const lv_font_t fms_b612_mono_32;

#ifdef __cplusplus
}
#endif
