#!/usr/bin/env python3
"""Rasterise the TTFs in assets/fonts into LVGL bitmap fonts.

Bitmaps rather than runtime FreeType: the glyph set is fixed and small, the sizes
are known, and a bitmap font costs no CPU and no heap at draw time.

    npm --prefix tools install lv_font_conv     # once
    python3 tools/gen_fonts.py                  # regenerate
    python3 tools/gen_fonts.py --gallery        # + the comparison candidates

Writes C sources into components/fmsui_fonts/, which both build targets compile.
"""

import argparse
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TTF_DIR = ROOT / "assets" / "fonts"
OUT_DIR = ROOT / "components" / "fmsui_fonts"
LV_FONT_CONV = ROOT / "tools" / "node_modules" / ".bin" / "lv_font_conv"

# What the FMS actually draws.  Latin, digits, punctuation, and the degree sign.
#
# Not the dropdown triangle, the arrows or the bullet: B612 Mono has no glyphs
# for them, and they are UI furniture rather than text anyway.  They get drawn as
# shapes by the widgets that need them (M3), which also means they scale and
# recolour with the widget instead of with the font.
RANGES = [
    "0x20-0x7E",  # printable ASCII
    "0xB0",       # DEGREE SIGN
]

# 4bpp anti-aliasing.  1bpp would be a third of the flash but the reference
# screens are clearly anti-aliased, and on a 294dpi panel the difference shows.
BPP = 4

# The size ladder, taken from the reference screenshots at 1280x720:
#   16 units and footnotes, 20 labels, 28 values, 32 titles
PRIMARY_SIZES = [16, 20, 24, 28, 32]

# Decided in M2: B612 Mono.  Airbus commissioned it from Intactile DESIGN, with
# ENAC, specifically for cockpit displays; it is the narrowest of the candidates,
# which matters on a page as dense as an FMS one; and it is what the reference
# screenshots look like.  SIL OFL 1.1.
#
# It has no dotted or slashed zero -- 0 and O are told apart by width alone.
# Neither does the real aircraft.  If that ever becomes unacceptable, the zero
# glyph can be edited (OFL permits it) and the font regenerated.
PRIMARY = ("B612Mono-Regular.ttf", "fms_b612_mono")

# The M2 comparison set.  Kept so the decision can be revisited: run with
# --gallery to regenerate them, then write a screen that renders the same content
# in each.
GALLERY = [
    ("B612Mono-Regular.ttf", "gal_b612_mono"),
    ("JetBrainsMono-Regular.ttf", "gal_jetbrains_mono"),
    ("IBMPlexMono-Regular.ttf", "gal_ibm_plex_mono"),
    ("MartianMono-Regular.ttf", "gal_martian_mono"),
]
GALLERY_SIZES = [20, 28, 48]  # 48 only so the 0/O question can actually be seen


def convert(ttf: pathlib.Path, name: str, size: int) -> pathlib.Path:
    out = OUT_DIR / f"{name}_{size}.c"
    cmd = [
        str(LV_FONT_CONV),
        "--font", str(ttf),
        "--size", str(size),
        "--bpp", str(BPP),
        "--format", "lvgl",
        "--lv-include", "lvgl.h",
        "--no-compress",
        "--force-fast-kern-format",
        "-o", str(out),
    ]
    for r in RANGES:
        cmd += ["-r", r]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"error converting {ttf.name} @ {size}px:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)

    print(f"  {out.name:<28} {out.stat().st_size // 1024:>4} kB")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gallery", action="store_true",
                    help="also build the comparison candidates (M2 only)")
    args = ap.parse_args()

    if not LV_FONT_CONV.exists():
        print("lv_font_conv not found. Run: npm --prefix tools install lv_font_conv",
              file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    generated = []

    print(f"{PRIMARY[0]}:")
    ttf, name = PRIMARY
    for size in PRIMARY_SIZES:
        generated.append((name, size, convert(TTF_DIR / ttf, name, size)))

    if args.gallery:
        for ttf, name in GALLERY:
            print(f"{ttf}:")
            for size in GALLERY_SIZES:
                generated.append((name, size, convert(TTF_DIR / ttf, name, size)))

    # One header declaring everything, so nothing has to hand-maintain externs.
    header = OUT_DIR / "include" / "fmsui_fonts.h"
    header.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* GENERATED by tools/gen_fonts.py -- do not edit. */",
        "",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for name, size, _ in generated:
        lines.append(f"extern const lv_font_t {name}_{size};")
    lines += [
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    header.write_text("\n".join(lines), encoding="utf-8")

    total = sum(p.stat().st_size for _, _, p in generated)
    print(f"\n{len(generated)} fonts, {total // 1024} kB of C source -> {OUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
