#!/usr/bin/env python3
"""Generate third_party/lv_conf.h from LVGL's lv_conf_template.h.

A single lv_conf.h is shared by both build targets (ESP-IDF and the SDL
simulator) so the two can never drift apart.  Platform differences are
expressed inside the file with `#ifdef ESP_PLATFORM`.

Re-run this after bumping the LVGL submodule.  Every edit asserts that it found
what it was looking for, so an upstream rename fails loudly rather than silently
leaving a default in place.  Value edits match on the `#define NAME` prefix only,
which survives the comment-style churn LVGL goes through between releases; block
edits match exactly, because there is no safe way to fuzzy-match those.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "third_party" / "lvgl" / "lv_conf_template.h"
OUTPUT = ROOT / "third_party" / "lv_conf.h"

HEADER = """/* GENERATED by tools/gen_lv_conf.py from lvgl/lv_conf_template.h -- edit the
 * generator, not this file.
 *
 * Shared by the ESP-IDF target and the SDL simulator.  Platform-specific
 * settings are guarded by ESP_PLATFORM.
 */
"""

# name -> replacement for the whole `#define name ...` line (indentation is kept)
DEFINES = {
    "LV_DPI_DEF": '#define LV_DPI_DEF 294  /* Tab5: 1280x720 on 5" -> ~294 dpi */',
    "LV_MEM_SIZE": "#define LV_MEM_SIZE (2 * 1024 * 1024U)",
    "LV_USE_LOG": "#define LV_USE_LOG 1",
    # LVGL's own fps overlay is off: it draws itself over the bottom-right corner
    # of whatever we built, and FmsApp::stats() already reports what it would.
    "LV_USE_SYSMON": "#define LV_USE_SYSMON 0",
    "LV_USE_PERF_MONITOR": "#define LV_USE_PERF_MONITOR 0",
    "LV_BUILD_EXAMPLES": "#define LV_BUILD_EXAMPLES 0",
    # Everything is drawn in B612 Mono (components/fmsui_fonts), so LVGL's stock
    # Montserrat sizes are flash we do not need. Montserrat 14 stays only because
    # LV_FONT_DEFAULT points at it, and a widget with no font set must still draw
    # something rather than crash.
    "LV_FONT_MONTSERRAT_16": "#define LV_FONT_MONTSERRAT_16 0",
    "LV_FONT_MONTSERRAT_20": "#define LV_FONT_MONTSERRAT_20 0",
    "LV_FONT_MONTSERRAT_24": "#define LV_FONT_MONTSERRAT_24 0",
    "LV_FONT_MONTSERRAT_28": "#define LV_FONT_MONTSERRAT_28 0",
    "LV_FONT_MONTSERRAT_32": "#define LV_FONT_MONTSERRAT_32 0",
    # Platform-conditional ones.
    "LV_USE_STDLIB_MALLOC": "\n".join([
        "#ifdef ESP_PLATFORM",
        "    /* Device: LVGL owns a pool carved out of PSRAM (see LV_MEM_POOL_ALLOC below). */",
        "    #define LV_USE_STDLIB_MALLOC    LV_STDLIB_BUILTIN",
        "#else",
        "    /* Simulator: plain malloc, so ASan can see every allocation. */",
        "    #define LV_USE_STDLIB_MALLOC    LV_STDLIB_CLIB",
        "#endif",
    ]),
    "LV_DRAW_BUF_ALIGN": "\n".join([
        "#ifdef ESP_PLATFORM",
        "    /* Align to the cache line so cache writeback of a draw buffer stays valid. */",
        "    #define LV_DRAW_BUF_ALIGN 64",
        "#else",
        "    #define LV_DRAW_BUF_ALIGN 4",
        "#endif",
    ]),
    "LV_LOG_PRINTF": "\n".join([
        "    #ifdef ESP_PLATFORM",
        "        #define LV_LOG_PRINTF 0  /* routed through esp_log by the port layer */",
        "    #else",
        "        #define LV_LOG_PRINTF 1",
        "    #endif",
    ]),
    # SDL is the simulator's window, mouse and keyboard, and nothing else wants
    # it. Off unless the build defines LV_USE_SDL itself -- sim/CMakeLists.txt
    # passes LV_USE_SDL=1 to LVGL -- so that an application building LVGL with
    # this file on a PC does not need SDL2's headers. The device never sets it.
    "LV_USE_SDL": "\n".join([
        "#ifndef LV_USE_SDL",
        "    /* Off unless the build turns it on: sim/CMakeLists.txt passes LV_USE_SDL=1. */",
        "    #define LV_USE_SDL 0",
        "#endif",
    ]),
}

# Exact multi-line replacements, for the things a per-define edit cannot express.
BLOCKS = [
    (
        "\n".join([
            "    #if LV_MEM_ADR == 0",
            "        #undef LV_MEM_POOL_INCLUDE",
            "        #undef LV_MEM_POOL_ALLOC",
            "    #endif",
        ]),
        "\n".join([
            "    #if LV_MEM_ADR == 0",
            "        #ifdef ESP_PLATFORM",
            "            /* Take the pool from PSRAM; 2MB will not fit in internal SRAM. */",
            '            #define LV_MEM_POOL_INCLUDE "esp_heap_caps.h"',
            "            #define LV_MEM_POOL_ALLOC(size) heap_caps_malloc(size, MALLOC_CAP_SPIRAM)",
            "        #else",
            "            #undef LV_MEM_POOL_INCLUDE",
            "            #undef LV_MEM_POOL_ALLOC",
            "        #endif",
            "    #endif",
        ]),
        "PSRAM pool on device",
    ),
]


def main() -> int:
    # The upstream template carries a UTF-8 BOM; prepending our header would
    # otherwise strand it mid-file, where it is a syntax error.
    text = TEMPLATE.read_text(encoding="utf-8-sig")

    # The template ships disabled behind `#if 0`.
    enabled, n = re.subn(r"^#if 0\b", "#if 1", text, count=1, flags=re.MULTILINE)
    if n != 1:
        print("error: could not find the leading `#if 0` guard", file=sys.stderr)
        return 1
    text = enabled

    for name, replacement in DEFINES.items():
        pattern = re.compile(rf"^([ \t]*)#define[ \t]+{re.escape(name)}\b.*$", re.MULTILINE)
        hits = pattern.findall(text)
        if len(hits) != 1:
            print(f"error: expected exactly one `#define {name}`, found {len(hits)}", file=sys.stderr)
            return 1
        indent = hits[0]
        # A multi-line replacement supplies its own indentation.
        body = replacement if "\n" in replacement else indent + replacement
        text = pattern.sub(lambda _m, b=body: b, text, count=1)

    for anchor, replacement, what in BLOCKS:
        if text.count(anchor) != 1:
            print(f"error: block anchor for '{what}' not found exactly once", file=sys.stderr)
            print(f"       looked for:\n{anchor}", file=sys.stderr)
            return 1
        text = text.replace(anchor, replacement)

    OUTPUT.write_text(HEADER + text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(DEFINES)} defines, {len(BLOCKS)} blocks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
